#!/bin/bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PG_ENV="$1"
source "$SCRIPT_PATH/../pg_util.bash"

TABLE_PERMS="permission"
TABLE_ROLES_PERMS="userroles_permissions"


pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('import_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('import_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_contacts_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_dba_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_dba_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_doc_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_doc_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_finance_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_finance_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_funding_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_funding_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_lenders_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_lenders_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_notes_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_notes_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_payment_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_payment_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_payrol_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_payrol_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_status_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_status_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_workflow_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_workflow_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('refdata_r', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('refdata_w', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('roles_commission', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('roles_iso', '');"
pg_execute "INSERT INTO ${TABLE_PERMS} (permission, description) VALUES ('mca_events_r', '');"


##### role_admin
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='import_r'       WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='import_w'       WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_contacts_w' WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_w'      WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_w'      WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_w'  WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_w'  WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_lenders_w'  WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_r'    WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_w'    WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payment_w'  WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payrol_w'   WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'   WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_w'   WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_w' WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='refdata_r'      WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='refdata_w'      WHERE r.property_name='role_admin';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_events_r'      WHERE r.property_name='role_admin';"

##### role_accounting_extern
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='import_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_lenders_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payment_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payrol_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_accounting_extern';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='refdata_r' WHERE r.property_name='role_accounting_extern';"

##### role_Underwriter
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_contacts_w' WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_w'      WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_w'      WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_w'  WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_w'  WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_r'    WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_w'    WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payment_r'  WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payrol_r'   WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payrol_w'   WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'   WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_w'   WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_w' WHERE r.property_name='role_Underwriter';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_contacts_w' WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_events_r' WHERE r.property_name='role_accounting';"

##### role_accounting
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r'      WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_r'      WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r'  WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_r'  WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_w'  WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_lenders_r'  WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_lenders_w'  WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_r'    WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_w'    WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payment_r'  WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payment_w'  WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payrol_r'   WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'   WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_w' WHERE r.property_name='role_accounting';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_events_r' WHERE r.property_name='role_accounting';"

##### role_collection
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_contacts_w' WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r'      WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_r'      WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_w'      WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r'  WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_r'  WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_lenders_r'  WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_r'    WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_w'    WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payment_r'  WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payrol_r'   WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'   WHERE r.property_name='role_collection';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_collection';"

##### role_OfficeManager
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r'      WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_w'      WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_r'      WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_w'      WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r'  WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_w'  WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_r'  WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_w'  WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_lenders_r'  WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_lenders_w'  WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_r'    WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_w'    WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payment_r'  WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payment_w'  WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payrol_r'   WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payrol_w'   WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'   WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_w'   WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_w' WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='refdata_r'      WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='refdata_w'      WHERE r.property_name='role_OfficeManager';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_events_r'      WHERE r.property_name='role_OfficeManager';"

##### role_iso_relations
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r'        WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_r'        WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r'    WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_r'    WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_lenders_r'    WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_r'      WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_w'      WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_payment_r'    WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'     WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r'   WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='roles_commission' WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='roles_iso'        WHERE r.property_name='role_iso_relations';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_events_r'        WHERE r.property_name='role_iso_relations';"

##### role_iso
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r'        WHERE r.property_name='role_iso';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_r'        WHERE r.property_name='role_iso';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r'    WHERE r.property_name='role_iso';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_r'    WHERE r.property_name='role_iso';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_lenders_r'    WHERE r.property_name='role_iso';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_notes_r'      WHERE r.property_name='role_iso';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'     WHERE r.property_name='role_iso';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='roles_commission' WHERE r.property_name='role_iso';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='roles_iso'        WHERE r.property_name='role_iso';"

##### role_dataentry
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r'      WHERE r.property_name='role_dataentry';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_w'      WHERE r.property_name='role_dataentry';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_w'      WHERE r.property_name='role_dataentry';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r'  WHERE r.property_name='role_dataentry';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_w'  WHERE r.property_name='role_dataentry';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'   WHERE r.property_name='role_dataentry';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_w'   WHERE r.property_name='role_dataentry';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_dataentry';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_w' WHERE r.property_name='role_dataentry';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_events_r' WHERE r.property_name='role_dataentry';"

##### role_UnderwriterLimited
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r'      WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_w'      WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_r'      WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_w'      WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r'  WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_w'  WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_r'  WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_funding_w'  WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'   WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_w'   WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_UnderwriterLimited';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_w' WHERE r.property_name='role_UnderwriterLimited';"

###### role_commission
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='roles_commission' WHERE r.property_name='role_commission';"

##### role_ins_commission
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='roles_commission' WHERE r.property_name='role_ins_commission';"

##### role_contract_fee
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='roles_commission' WHERE r.property_name='role_contract_fee';"

##### role_email_mgmt
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r'      WHERE r.property_name='role_email_mgmt';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_w'      WHERE r.property_name='role_email_mgmt';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_w'      WHERE r.property_name='role_email_mgmt';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r'  WHERE r.property_name='role_email_mgmt';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_w'  WHERE r.property_name='role_email_mgmt';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'   WHERE r.property_name='role_email_mgmt';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_w'   WHERE r.property_name='role_email_mgmt';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_email_mgmt';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_w' WHERE r.property_name='role_email_mgmt';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_events_r' WHERE r.property_name='role_email_mgmt';"

##### role_uw_calc
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_r'      WHERE r.property_name='role_uw_calc';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_dba_w'      WHERE r.property_name='role_uw_calc';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_doc_w'      WHERE r.property_name='role_uw_calc';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_r'  WHERE r.property_name='role_uw_calc';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_finance_w'  WHERE r.property_name='role_uw_calc';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_r'   WHERE r.property_name='role_uw_calc';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_status_w'   WHERE r.property_name='role_uw_calc';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_r' WHERE r.property_name='role_uw_calc';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_workflow_w' WHERE r.property_name='role_uw_calc';"
pg_execute "INSERT INTO ${TABLE_ROLES_PERMS} (role_id, permission_id) SELECT r.id as role_id, p.id AS permission_id FROM userrole r LEFT JOIN permission p ON p.permission='mca_events_r' WHERE r.property_name='role_uw_calc';"
